### ISSUE TITLE
Music makes cracking noise

### ISSUE THREAD

**Issue by KlaraJa** [jellespijker/elevated_beats_n_slices#7]
Hi,

I don't know if this a MacOS specific problem, but the music sometimes makes loud cracking noises.

Regards,
Klara

**Comment by jellespijker** [comment]
Hi @KlaraJa thanks for reporting this issue. I have not experienced this on my Mac. It might be related to the mp3 which is shipped with the plugin. Can you try what happens if you play the mp3 in your normal player? You can download it here: https://github.com/jellespijker/elevated_beats_n_slices/blob/main/resources/waiting-music-116216.mp3

It would also help to have a bit more info on Which Cura version you use and what your Mac version and architecture is: Intel/M1 etc.

**Comment by KlaraJa** [comment]
Hi @jellespijker,

I'm using a Macbook Pro with a M1 Pro chip.

Cura version: 5.4.0

When I replay in VLC on my Mac do not have any issues.

By myself I'm not familiar with the Cure file structure, can you tell me where the mp3 is in the Cura files? Then i could check if this file is corrupt on my side.

**Comment by jellespijker** [comment]
Hi @KlaraJa sorry it took me some while to get back to you, work got in between. The easiest way to get to the specific user files and plugins in Cura is to click the menu `help` -> `Show Configuration Folder`. The `mp3` for plugin itself is located in `plugins/ElevatedBeatsnSlices/ElevatedBeatsnSlices/resources/`

You can also replace this mp3 file with any file you like

**Comment by KlaraJa** [comment]
Hi @jellespijker,
after listening to this whole (wonderful) song, i can verify that the not present with VLC, it was perfectly fine.

In the meantime Cure released the version 5.5.0 and i tried it in the app again and did not have any cracking noises. (In the 5 seconds time it takes).

Maybe it was a bug with Cura?

I think you could close the Issue and I will make a new one if this continues again, if this is okay with you?

**Comment by jellespijker** [comment]
Sounds good. Thank you for testing.
